### ISSUE TITLE
Undo feature?

### ISSUE THREAD

**Issue by pbill2003** [alistairbill/evohome-charts#1]
Enhancement. User error (misplaced clicking) in a room setpoint bar chart causes the schedule for that day to disappear or otherwise get very messed up. User would like to reinstate the schedule in that bar chart easily, rather than having to rebuild from memory.  Please. Dz.

**Comment by alistairbill** [comment]
I've deployed a new version with a simple undo feature (reverses the last change). Could also add a more advanced undo/redo feature if it's required

**Comment by pbill2003** [comment]
Fab. Thanks. Works as requested. Nothing more complex needed (for the moment ;-) )
