### ISSUE TITLE
question: can you change a schedule of oenywell evohome with that app

### ISSUE THREAD

**Issue by mptheone** [alistairbill/evohome-charts#5]
so what is your charts app doing?

**Comment by alistairbill** [comment]
This project provides a user interface for editing the 'zone schedule' JSON files you get from https://evohome.readthedocs.io/en/latest/api2/backuprestore.html - you probably want https://github.com/watchforstock/evohome-client instead.

**Comment by mptheone** [comment]
and that really works, so you can change a schedule completly and load it back?
